/* Fix script parsing and provide stable behavior on every page. */
const isEnglish = /^\/en(?:\/|$)/i.test(window.location.pathname);
const currentLang = isEnglish ? 'en' : 'ar';
const translations = {
  ar:{home:'الرئيسية',cities:'المدن',hotels:'الفنادق',landmarks:'المعالم',museums:'المتاحف',transport:'النقل',restaurants:'المطاعم',articles:'مقالات',support:'دعم الموقع',langSwitch:'EN',readMore:'اقرأ المزيد',viewAll:'عرض الكل',searchPlaceholder:'ابحث عن مدينة، فندق، معلم...',contactUs:'اتصل بنا',quickLinks:'روابط سريعة',rights:'جميع الحقوق محفوظة'},
  en:{home:'Home',cities:'Cities',hotels:'Hotels',landmarks:'Landmarks',museums:'Museums',transport:'Transport',restaurants:'Restaurants',articles:'Articles',support:'Support',langSwitch:'AR',readMore:'Read More',viewAll:'View All',searchPlaceholder:'Search for a city, hotel or landmark...',contactUs:'Contact Us',quickLinks:'Quick Links',rights:'All Rights Reserved'}
};
const navItems=[['index.html','home'],['cities.html','cities'],['hotels.html','hotels'],['landmarks.html','landmarks'],['museums.html','museums'],['transport.html','transport'],['restaurants.html','restaurants'],['support.html','support']];
function pagePath(){let p=window.location.pathname.replace(/\\/g,'/');p=p.replace(/^.*?\/en(?=\/|$)/i,'').replace(/\/index\.html$/i,'/');return p||'/';}
function languageUrl(target){return (target==='en'?'/en'+pagePath():pagePath()).replace(/\/+/g,'/');}
function toggleLanguage(){window.location.href=languageUrl(currentLang==='ar'?'en':'ar');}
window.toggleLanguage=toggleLanguage;
function localHref(path){return isEnglish?(`/en/${path}`).replace(/\/+/g,'/'):path;}
function renderNavigation(){const t=translations[currentLang];document.querySelectorAll('.nav-links,.mobile-menu-links').forEach(list=>{if(!list.children.length||list.id==='navLinks'||list.id==='mobileMenuLinks')list.innerHTML=navItems.map(([href,key])=>`<li><a href="${localHref(href)}" data-key="${key}">${t[key]}</a></li>`).join('');});}
function ensureLanguageButton(){let b=document.getElementById('langToggle');const actions=document.querySelector('.nav-actions');if(!b&&actions){b=document.createElement('button');b.id='langToggle';b.className='lang-toggle';b.type='button';actions.prepend(b);}if(b){b.textContent=translations[currentLang].langSwitch;b.onclick=toggleLanguage;b.setAttribute('aria-label',currentLang==='ar'?'Switch to English':'التبديل إلى العربية');}}
function ensureMobileMenu(){let m=document.querySelector('.mobile-menu');if(!m){m=document.createElement('aside');m.className='mobile-menu';m.innerHTML='<button class="mobile-menu-close" type="button" aria-label="Close menu">×</button><ul class="mobile-menu-links"></ul>';document.body.appendChild(m);}let o=document.querySelector('.mobile-menu-overlay');if(!o){o=document.createElement('div');o.className='mobile-menu-overlay';document.body.appendChild(o);}const list=m.querySelector('.mobile-menu-links');if(list&&!list.children.length)list.innerHTML=navItems.map(([href,key])=>`<li><a href="${localHref(href)}" data-key="${key}">${translations[currentLang][key]}</a></li>`).join('');const b=document.querySelector('.mobile-menu-btn');if(!b)return;const close=()=>{m.classList.remove('active','open');o.classList.remove('active');b.setAttribute('aria-expanded','false');document.body.style.overflow='';};b.onclick=()=>{m.classList.add('active','open');o.classList.add('active');b.setAttribute('aria-expanded','true');document.body.style.overflow='hidden';};m.querySelector('.mobile-menu-close')?.addEventListener('click',close);o.addEventListener('click',close);m.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));}
function applyTranslations(){const t=translations[currentLang];document.documentElement.lang=currentLang;document.documentElement.dir=currentLang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-key]').forEach(e=>{const v=t[e.dataset.key];if(v)e.tagName==='INPUT'?e.placeholder=v:e.textContent=v;});ensureLanguageButton();}
function updateSEO(){const ar=location.origin+pagePath(),en=location.origin+languageUrl('en');let c=document.querySelector('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c);}c.href=currentLang==='en'?en:ar;[['ar',ar],['en',en],['x-default',ar]].forEach(([code,href])=>{let link=document.querySelector(`link[rel="alternate"][hreflang="${code}"]`);if(!link){link=document.createElement('link');link.rel='alternate';link.hreflang=code;document.head.appendChild(link);}link.href=href;});}
function makeCardsInteractive(){document.querySelectorAll('.card,.mini-card,.scroll-card').forEach(card=>{const a=card.querySelector('a[href]');if(!card.dataset.href&&a)card.dataset.href=a.getAttribute('href');if(!card.dataset.href)return;card.setAttribute('tabindex',card.getAttribute('tabindex')||'0');const go=()=>{window.location.href=card.dataset.href;};card.addEventListener('click',e=>{if(!e.target.closest('a,button'))go();});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('a,button')){e.preventDefault();go();}});});}
function initSearch(){document.querySelectorAll('.search-bar input').forEach(i=>i.addEventListener('input',()=>{const q=i.value.trim().toLocaleLowerCase();document.querySelectorAll('[data-search]').forEach(x=>x.hidden=!!q&&!x.dataset.search.toLocaleLowerCase().includes(q));}));}
function initNavbar(){const n=document.querySelector('.navbar');if(!n)return;const update=()=>n.classList.toggle('scrolled',window.scrollY>40);window.addEventListener('scroll',update,{passive:true});update();}
document.addEventListener('DOMContentLoaded',()=>{renderNavigation();applyTranslations();ensureMobileMenu();updateSEO();makeCardsInteractive();initSearch();initNavbar();});
